sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.5
  - 2.7
  - ruby-head
  - jruby-head
  - jruby-9.2.13.0
  - truffleruby
  - truffleruby-head
before_install:
  - gem install bundler -v 1.17.3
git:
  submodules: false
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: 2.5
      gemfile: gemfiles/miniracer
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
    - rvm: truffleruby-head
  fast_finish: true
